Migrate to null safety
Workiva/dart_dev pull request #402
Opened 2023-03-02 23:45 UTC by robbecker-wf

WIP DRAFT #2 to convert to null safety

2023-03-02 23:46 UTC, aviary2-wf commented
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

2023-03-10 19:05 UTC, evanweible-wf requested changes

2023-03-10 19:05 UTC, evanweible-wf commented on test/functional/documentation_test.dart
> +  final Set<String?> packages;
I think we can make this non-nullable if we fix up the parsing below

2023-03-10 20:27 UTC, evanweible-wf approved these changes

2023-03-10 21:16 UTC, robbecker-wf commented
QA+1 CI Passes and manually tested in a few other packages. Tried test, analyze, format, and server tasks.

2023-03-10 21:18 UTC, evanweible-wf commented
semver +1
@Workiva/release-management-p

2023-03-10 21:18 UTC, rmconsole-wf approved these changes
+1 from RM

2023-03-10 21:18 UTC, merged